name: CI/CD Pipeline

on:
  push:
    branches:
      - Test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: thanhtinh
          MYSQL_DATABASE: foody
          MYSQL_USER: thanhtinh
          MYSQL_PASSWORD: new_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0' # Thay đổi phiên bản nếu cần

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Create MySQL User
        run: |
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e "CREATE USER 'runner'@'%' IDENTIFIED BY 'your_runner_password';"
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e "GRANT ALL PRIVILEGES ON foody.* TO 'runner'@'%'; FLUSH PRIVILEGES;"
        env:
          MYSQL_ROOT_PASSWORD: thanhtinh

      - name: Run Tests
        run: npm test

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Start LocalTunnel
        run: |
          # Khởi động LocalTunnel
          lt --port 8080 --subdomain mycustomsubdomain > tunnel_url.txt &
          sleep 5 # Chờ một chút cho LocalTunnel khởi động

          # Đọc URL của LocalTunnel
          LOCAL_TUNNEL_URL=$(cat tunnel_url.txt)
          echo "LocalTunnel URL: $LOCAL_TUNNEL_URL"

      - name: Deploy Application
        run: |
          # Ở đây bạn có thể thực hiện các bước deploy cần thiết như 
          # git pull, npm install, hoặc các lệnh khác mà bạn cần
          echo "Deploying application..."
          # Lệnh deploy cụ thể của bạn ở đây
