name: CI/CD Pipeline

on:
  push:
    branches:
      - Test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: thanhtinh
          MYSQL_DATABASE: foody
          MYSQL_USER: thanhtinh
          MYSQL_PASSWORD: new_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Create MySQL User
        run: |
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e "CREATE USER 'runner'@'%' IDENTIFIED BY 'your_runner_password';"
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e "GRANT ALL PRIVILEGES ON foody.* TO 'runner'@'%'; FLUSH PRIVILEGES;"
        env:
          MYSQL_ROOT_PASSWORD: thanhtinh

      - name: Run Tests
        run: npm test

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.24.150.195 >> ~/.ssh/known_hosts

      - name: Check SSH Connectivity
        run: |
          echo "Checking SSH connectivity..."
          timeout 5 bash -c "until ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ThanhTinh@172.24.150.195 'exit'; do echo 'Waiting for SSH...'; sleep 5; done"

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ThanhTinh@172.24.150.195 "cd /home/Backend/src && git pull origin main && npm install && pm2 restart your-app"
